document.write("<style type=",'"',"text/css",'"',">\n")
document.write("<!--\n")
document.write("\n")
document.write(".tooltiptitle{COLOR: #000000; TEXT-DECORATION: none; CURSOR: Default; font-family: arial; font-weight: bold; font-size: 9pt}\n")
document.write(".tooltipcontent{COLOR: #000000; TEXT-DECORATION: none; CURSOR: Default; font-family: arial; font-size: 9pt}\n")
document.write("\n")
document.write("#ToolTip{position:absolute; width: 300px; top: 0px; left: 200px; z-index:4; visibility:hidden;}\n")
document.write("\n")
document.write("-->\n")
document.write("</style>\n")
document.write("\n")
document.write("<scr","ipt language = ",'"',"javascr","ipt",'"',">\n")
document.write("<!--\n")
document.write("\n")
document.write("var left_ind = 0\n")
document.write("var ie = document.all ? 1 : 0\n")
document.write("var ns = document.layers ? 1 : 0\n")
document.write("\n")
document.write("if(ns){doc = ",'"',"document.",'"',"; sty = ",'"',"",'"',"}\n")
document.write("if(ie){doc = ",'"',"document.all.",'"',"; sty = ",'"',".style",'"',"}\n")
document.write("\n")
document.write("var initialize = 0\n")
document.write("var Ex, Ey, topColor, subColor, ContentInfo\n")
document.write("\n")
document.write("if(ie){\n")
document.write("Ex = ",'"',"event.x",'"',"\n")
document.write("Ey = ",'"',"event.y",'"',"\n")
document.write("\n")
document.write("topColor = ",'"',"#AEAEAE",'"',"\n")
document.write("subColor = ",'"',"#F2F2F2",'"',"\n")
document.write("}\n")
document.write("\n")
document.write("if(ns){\n")
document.write("Ex = ",'"',"e.pageX",'"',"\n")
document.write("Ey = ",'"',"e.pageY",'"',"\n")
document.write("window.captureEvents(Event.MOUSEMOVE)\n")
document.write("window.onmousemove=overhere\n")
document.write("\n")
document.write("topColor = ",'"',"#AEAEAE",'"',"\n")
document.write("subColor = ",'"',"#F2F2F2",'"',"\n")
document.write("}\n")
document.write("\n")
document.write("function MoveToolTip(layerName, FromTop, FromLeft, e){\n")
document.write("if(ie){eval(doc + layerName + sty + ",'"',".top = ",'"',"  + (eval(FromTop) + document.body.scrollTop))}\n")
document.write("if(ns){eval(doc + layerName + sty + ",'"',".top = ",'"',"  +  (eval(FromTop) + 20))}\n")
document.write("eval(doc + layerName + sty + ",'"',".left = ",'"'," + (eval(FromLeft) + left_ind))\n")
document.write("}\n")
document.write("\n")
document.write("function ReplaceContent(layerName){\n")
document.write("\n")
document.write("if(ie){document.all[layerName].innerHTML = ContentInfo}\n")
document.write("\n")
document.write("\n")
document.write("if(ns){\n")
document.write("\n")
document.write("with(document.layers[layerName].document) \n")
document.write("{ \n")
document.write("   open(); \n")
document.write("   write(ContentInfo); \n")
document.write("   close(); \n")
document.write("}\n")
document.write("\n")
document.write("}\n")
document.write("}\n")
document.write("\n")
document.write("function Activate(){initialize=1}\n")
document.write("function deActivate(){initialize=0}\n")
document.write("\n")
document.write("\n")
document.write("function overhere(e){\n")
document.write("if(initialize){\n")
document.write("\n")
document.write("MoveToolTip(",'"',"ToolTip",'"',", Ey, Ex, e)\n")
document.write("eval(doc + ",'"',"ToolTip",'"'," + sty + ",'"',".visibility = 'visible'",'"',")\n")
document.write("}\n")
document.write("\n")
document.write("else{\n")
document.write("MoveToolTip(",'"',"ToolTip",'"',", 0, 0)\n")
document.write("eval(doc + ",'"',"ToolTip",'"'," + sty + ",'"',".visibility = 'hidden'",'"',")\n")
document.write("}\n")
document.write("\n")
document.write("\n")
document.write("}\n")
document.write("function EnterContent(layerName, TTitle, TContent, LDir){\n")
document.write("if(LDir == 'rtl') left_ind = 0; else left_ind = -300;\n")
document.write("\n")
document.write("ContentInfo = '<table dir='+LDir+' border=",'"',"0",'"'," width=",'"',"300",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"0",'"',">'+\n")
document.write("'<tr><td width=",'"',"100%",'"'," bgcolor=",'"',"#000000",'"',">'+\n")
document.write("\n")
document.write("'<table border=",'"',"0",'"'," width=",'"',"100%",'"'," cellspacing=",'"',"1",'"'," cellpadding=",'"',"0",'"',">'+\n")
document.write("'<tr><td width=",'"',"100%",'"'," bgcolor='+topColor+'>'+\n")
document.write("\n")
document.write("'<table border=",'"',"0",'"'," width=",'"',"98%",'"'," cellspacing=",'"',"0",'"'," cellpadding=",'"',"1",'"'," align=",'"',"center",'"',">'+\n")
document.write("'<tr><td width=",'"',"100%",'"',">'+\n")
document.write("\n")
document.write("'<font class=",'"',"tooltiptitle",'"',">&nbsp;'+unescape(TTitle)+'</font>'+\n")
document.write("\n")
document.write("'</td></tr>'+\n")
document.write("'</table>'+\n")
document.write("\n")
document.write("'</td></tr>'+\n")
document.write("\n")
document.write("'<tr><td width=",'"',"100%",'"'," bgcolor='+subColor+'>'+\n")
document.write("\n")
document.write("'<table border=",'"',"0",'"'," width=",'"',"98%",'"'," cellpadding=",'"',"2",'"'," cellspacing=",'"',"1",'"'," align=",'"',"center",'"',">'+\n")
document.write("\n")
document.write("'<tr><td width=",'"',"100%",'"',">'+\n")
document.write("\n")
document.write("'<font class=",'"',"tooltipcontent",'"',">'+unescape(TContent)+'</font>'+\n")
document.write("\n")
document.write("'</td></tr>'+\n")
document.write("'</table>'+\n")
document.write("\n")
document.write("'</td></tr>'+\n")
document.write("'</table>'+\n")
document.write("\n")
document.write("'</td></tr>'+\n")
document.write("'</table>';\n")
document.write("\n")
document.write("\n")
document.write("ReplaceContent(layerName)\n")
document.write("\n")
document.write("\n")
document.write("}\n")
document.write("//-->\n")
document.write("</scr","ipt>\n")