<%
'Chart types
const PIE_CHART = 0
const LINE_CHART = 1
const SCATTER_LINE_CHART = 2
const SCATTER_CHART = 3
const BAR_CHART = 4
const STACKED_BAR_CHART= 5
const COLUMN_CHART = 6
const STACKED_COLUMN_CHART = 7
const AREA_CHART = 8 
const STOCK_CHART = 9
const CANDLESTICK_CHART = 10
const STACKED_AREA_CHART = 11

'Axis index
const LEFT_AXIS = 0
const BOTTOM_AXIS = 1
const RIGHT_AXIS = 2
const TOP_AXIS = 3

'Font Styles:
const FONT_REGULAR = 0
const FONT_BOLD = 1
const FONT_ITALIC = 2
const FONT_BOLDITALIC = 3

'Label alignments
const CENTER = 0
const TOP_CENTER = 1
const TOP_LEFT = 2
const LEFT_CENTER = 3
const BOTTOM_LEFT = 4
const BOTTOM_CENTER = 5
const BOTTOM_RIGHT = 6
const RIGHT_CENTER = 7
const TOP_RIGHT = 8

'Marker types
const MARKER_SQUARE = 0
const MARKER_CIRCLE = 1
const MARKER_DIAMOND = 2
const MARKER_TRIANGLE = 3
const MARKER_CROSS = 4
%>